services:
  postgres_db_dev:
    image: postgres:15-alpine
    container_name: attendance_postgres_dev
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: attendance_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - attendance_dev_net
    restart: unless-stopped
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U devuser -d attendance_dev"]
        interval: 10s
        timeout: 5s
        retries: 5

  backend:
    container_name: attendance_backend_dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npx ts-node-dev --respawn --transpile-only src/server.ts
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      postgres_db_dev:
        condition: service_healthy
    env_file:
      - ./backend/.env.development
    networks:
      - attendance_dev_net
    restart: unless-stopped
    stdin_open: true
    tty: true

  frontend:
    container_name: attendance_frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - attendance_dev_net
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  postgres_dev_data:
    driver: local

networks:
  attendance_dev_net:
    driver: bridge