services:
    backend:
        image: us-central1-docker.pkg.dev/pivotal-gearbox-451115-q1/attendance-repo-multiarch/attendance-tracker-backend:main
        platform: linux/amd64
        container_name: attendance_backend_production
        restart: always
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - PORT=3000
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_EXPIRES_IN=7d
            - FRONTEND_URL=https://timetable.leverage.blog
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - GOOGLE_CALLBACK_URL=https://timetable.leverage.blog/api/v1/auth/google/callback
        networks:
            - attendance_production_net
        healthcheck:
            test: ['CMD-SHELL', 'wget -q --spider http://localhost:3000/api/v1/health || exit 1']
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s

    frontend:
        image: us-central1-docker.pkg.dev/pivotal-gearbox-451115-q1/attendance-repo-multiarch/attendance-tracker-frontend:main
        container_name: attendance_frontend_production
        restart: always
        networks:
            - attendance_production_net
        expose:
            - '80'

    nginx:
        image: nginx:1.25-alpine
        platform: linux/amd64
        container_name: attendance_nginx_production
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - frontend
            - backend
        networks:
            - attendance_production_net

networks:
    attendance_production_net:
        driver: bridge
