version: '3.8'

services:
  postgres_db_dev: # Renamed service for clarity
    image: postgres:15-alpine
    container_name: attendance_postgres_dev
    environment:
      # These MUST match the DATABASE_URL in backend/.env.development
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: attendance_dev
    ports:
      - "5432:5432" # Expose standard PG port on host
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - attendance_dev_net
    restart: unless-stopped

  backend:
    container_name: attendance_backend_dev
    # Build from backend directory using its Dockerfile
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Command to run dev server with hot-reloading
    command: npm run dev
    volumes:
      # Mount source code (except node_modules)
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      # Mount other necessary files like tsconfig, package.json if needed by dev process
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      # Use a named volume for node_modules to prevent overwriting
      - backend_node_modules:/app/node_modules
    ports:
      - "3001:3001" # Expose backend API port
    depends_on:
      - postgres_db_dev
    # Load environment variables from the specified file
    env_file:
      - ./backend/.env.development
    networks:
      - attendance_dev_net
    restart: unless-stopped

  frontend:
    container_name: attendance_frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile # Uses the simplified Dockerfile
      # Pass VITE_API_BASE_URL during build if needed by production build
      # args:
      #   VITE_API_BASE_URL: http://localhost:3001/api/v1 # Or /api/v1 if proxying
    # Command to run Vite dev server
    # --host exposes it outside the container
    command: npm run dev -- --host
    volumes:
      # Mount source code (except node_modules)
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      # Mount other necessary files
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
      # Use a named volume for node_modules
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173" # Expose Vite dev server port
    # Vite dev server reads .env.development automatically from context
    # env_file:
    #   - ./frontend/.env.development # Usually not needed for Vite dev server
    depends_on:
      - backend
    networks:
      - attendance_dev_net
    restart: unless-stopped

volumes:
  postgres_dev_data:
  backend_node_modules: # Persist backend node_modules
  frontend_node_modules: # Persist frontend node_modules

networks:
  attendance_dev_net:
    driver: bridge