services:
  backend:
    image: asia-south1-docker.pkg.dev/pivotal-gearbox-451115-q1/attendance-repo-multiarch/attendance-backend:latest
    platform: linux/amd64
    container_name: attendance_backend_staging
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - PORT=3000
      - DATABASE_URL=${AIVEN_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET:-staging-jwt-secret}
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:80
    networks:
      - attendance_staging_net
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    image: asia-south1-docker.pkg.dev/pivotal-gearbox-451115-q1/attendance-repo-multiarch/attendance-frontend:latest
    container_name: attendance_frontend_staging
    restart: always
    networks:
      - attendance_staging_net
    expose:
      - "80"

  nginx:
    image: nginx:1.25-alpine
    platform: linux/amd64
    container_name: attendance_nginx_staging
    restart: always
    ports:
      - "8080:80"  # Different port for staging
    volumes:
      - ./nginx.reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - attendance_staging_net

networks:
  attendance_staging_net:
    driver: bridge
