services:
    postgres_db_dev:
        image: postgres:15-alpine
        container_name: attendance_postgres_dev_prod_test
        environment:
            POSTGRES_USER: devuser
            POSTGRES_PASSWORD: devpassword
            POSTGRES_DB: attendance_dev
        ports:
            - '5432:5432' # Map host 5432 to container 5432 (ensure nothing else uses 5432 on host)
        volumes:
            - postgres_dev_data:/var/lib/postgresql/data
        networks:
            - attendance_local_prod_net
        restart: unless-stopped
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U devuser -d attendance_dev']
            interval: 10s
            timeout: 5s
            retries: 5

    backend:
        container_name: attendance_backend_prod_test
        build:
            context: ./backend
            dockerfile: Dockerfile # Assumes backend/Dockerfile is production multi-stage
        restart: always
        # Uses CMD ["node", "dist/server.js"] from Dockerfile
        volumes:
            # Only mount prisma if running migrations via exec, otherwise none needed
            - ./backend/prisma:/app/prisma
        expose:
            - '3001' # Expose internally for nginx proxy
        ports:
            - "3001:3001"
        depends_on:
            postgres_db_dev:
                condition: service_healthy
        env_file:
            - ./backend/.env.development # Use dev env for DB connection etc.
        environment:
            - NODE_ENV=production # CRITICAL: Run backend code in production mode
            # Ensure FRONTEND_URL in .env.development points to the proxy port (e.g., http://localhost:8080)
        networks:
            - attendance_local_prod_net
        healthcheck: # Use backend's healthcheck
            test: ['CMD-SHELL', 'wget -q --spider http://localhost:3001/api/v1/health || exit 1']
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s

    frontend:
        container_name: attendance_frontend_prod_test
        build:
            context: ./frontend
            dockerfile: Dockerfile # Assumes frontend/Dockerfile uses Nginx
            args:
                # Ensure API calls go through the reverse proxy
                VITE_API_BASE_URL: /api/v1
        restart: always
        # Uses CMD ["nginx", "-g", "daemon off;"] from Dockerfile
        expose:
            - '80' # Expose Nginx port internally
        networks:
            - attendance_local_prod_net
        depends_on: # Logical dependency
            - backend

    nginx:
        image: nginx:1.25-alpine
        container_name: attendance_nginx_proxy_test
        restart: always
        ports:
            # Map host port 8080 to proxy container port 80
            - '8080:80'
            # - "443:443" # For HTTPS later
        volumes:
            # Mount the reverse proxy config from project root
            - ./nginx.reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - frontend
            - backend
        networks:
            - attendance_local_prod_net

volumes:
    postgres_dev_data:
        driver: local

networks:
    attendance_local_prod_net:
        driver: bridge
