services:
  backend:
    image: ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPO_NAME}/attendance-backend:${IMAGE_TAG}
    platform: linux/amd64
    container_name: attendance_backend_prod
    restart: always
    env_file:
      - .env.backend.prod
    networks:
      - attendance_prod_net
    expose:
      - "3001"
    healthcheck:
        test: ["CMD-SHELL", "wget -q --spider http://localhost:3001/api/v1/health || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s

  frontend:
    image: ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPO_NAME}/attendance-frontend:${IMAGE_TAG}
    container_name: attendance_frontend_prod
    restart: always
    networks:
      - attendance_prod_net
    expose:
      - "80"

  nginx:
    image: nginx:1.25-alpine
    platform: linux/amd64
    container_name: attendance_nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - attendance_prod_net

networks:
  attendance_prod_net:
    driver: bridge